language: julia
os:
  - linux
  - osx
julia:
  - 0.5
  - 0.6
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
sudo: false
cache:
  directories:
    - /home/travis/.julia
addons:
  apt_packages:
    - gfortran
    - liblapack-dev
    - libgmp-dev
    - libglpk-dev

before_install:
  - julia -e 'if "AmplNLWriter" in keys(Pkg.installed()) Pkg.rm("AmplNLWriter"); Pkg.rm("AmplNLWriter") end'
  - julia -e 'Pkg.update()' #make sure we get the latest version of METADATA
  - julia -e 'if !("Cbc" in keys(Pkg.installed())) Pkg.add("Cbc") end'
  - julia -e 'if !("Ipopt" in keys(Pkg.installed())) Pkg.add("Ipopt") end'
  - julia -e 'if !("CoinOptServices" in keys(Pkg.installed())) Pkg.add("CoinOptServices") end'

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("AmplNLWriter"); Pkg.test("AmplNLWriter")'

# TBD
#after_success:
#  - julia -e  'using Coverage; cd(Pkg.dir("AmplNLWriter")); LCOV.writefile("lcov.info", process_folder(".")); run(pipeline(`curl -s https://codecov.io/bash`, `bash`))'
#  - julia -e 'cd(Pkg.dir("AmplNLWriter")); include(joinpath("docs", "make.jl"))'