language: julia
os:
  - linux
  - osx
julia:
  - 0.6
notifications:
  email: false
sudo: false
cache:
  directories:
  - $HOME/usr
addons:
  apt_packages:
  - gfortran
env:
  - MAKEFLAGS="-j3"
    LD_LIBRARY_PATH=$HOME/usr/lib
# Override the default test script
# We need to add `Cbc`, `Ipopt` and `CoinOptServices` manually so we can cache
# them after the tests have run
script:
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("AmplNLWriter"); Pkg.add("Ipopt"); Pkg.test("AmplNLWriter")'
before_cache:
  - cp -R $HOME/.julia/*/Ipopt/deps/usr $HOME
after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("AmplNLWriter")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
