name: MINLPTests
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    name: Julia ${{ github.event_name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
          arch: x64
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
      - name:
        shell: julia --color=yes {0}
        run: |
          amplnlwriter = ENV["GITHUB_WORKSPACE"]
          path = joinpath(amplnlwriter, "test", "MINLPTests")
          cd(path)
          using Pkg
          Pkg.activate(".")
          Pkg.instantiate()
          Pkg.add(PackageSpec(path=amplnlwriter))
          include(joinpath(path, "run_minlptests.jl"))
